#!/bin/bash

# Gmail OAuth2 Setup Script
# This script helps you get the OAuth2 credentials for Gmail

echo "=== Gmail OAuth2 Setup Guide ==="
echo ""
echo "Follow these steps to get your OAuth2 credentials:"
echo ""
echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
echo "2. Create a new project or select an existing one"
echo "3. Enable the Gmail API:"
echo "   - Go to 'APIs & Services' > 'Library'"
echo "   - Search for 'Gmail API'"
echo "   - Click on it and press 'Enable'"
echo ""
echo "4. Create OAuth2 credentials:"
echo "   - Go to 'APIs & Services' > 'Credentials'"
echo "   - Click 'Create Credentials' > 'OAuth client ID'"
echo "   - Choose 'Web application'"
echo "   - Add authorized redirect URI: https://developers.google.com/oauthplayground"
echo ""
echo "5. Get refresh token:"
echo "   - Go to: https://developers.google.com/oauthplayground/"
echo "   - Click the gear icon (⚙️) and check 'Use your own OAuth credentials'"
echo "   - Enter your Client ID and Client Secret"
echo "   - In Step 1, enter: https://www.googleapis.com/auth/gmail.send"
echo "   - Click 'Authorize APIs'"
echo "   - In Step 2, click 'Exchange authorization code for tokens'"
echo "   - Copy the 'Refresh token'"
echo ""
echo "6. Update your .env file with:"
echo "   - GMAIL_CLIENT_ID=your-client-id"
echo "   - GMAIL_CLIENT_SECRET=your-client-secret" 
echo "   - GMAIL_REFRESH_TOKEN=your-refresh-token"
echo "   - GMAIL_USER=your-gmail-address"
echo ""
echo "Done! Your mailer API will be ready to send emails."